kind = "web"
previewPath = "/"
title = "Go Ukraina Website"
version = "1.0.0"
id = "artifacts/goukraina-website"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22379

[services.development]
run = "pnpm --filter @workspace/goukraina-website run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/goukraina-website", "run", "build" ]
publicDir = "artifacts/goukraina-website/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22379"
BASE_PATH = "/"
